# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from solenoid_ctrl/solenoid_status.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class solenoid_status(genpy.Message):
  _md5sum = "f071f78c9fde6c43f4fb013e9d377f82"
  _type = "solenoid_ctrl/solenoid_status"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Reports the solenoid and control state of the solenoid_ctrl package
bool sol_ctrl        # indicates whether key_sub is in control mode
bool sol_bear        # indicates the status of the air bearing solenoid valve
int16[] sol_thrust   # indicates the status of the thruster air bearings

"""
  __slots__ = ['sol_ctrl','sol_bear','sol_thrust']
  _slot_types = ['bool','bool','int16[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sol_ctrl,sol_bear,sol_thrust

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(solenoid_status, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.sol_ctrl is None:
        self.sol_ctrl = False
      if self.sol_bear is None:
        self.sol_bear = False
      if self.sol_thrust is None:
        self.sol_thrust = []
    else:
      self.sol_ctrl = False
      self.sol_bear = False
      self.sol_thrust = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2B().pack(_x.sol_ctrl, _x.sol_bear))
      length = len(self.sol_thrust)
      buff.write(_struct_I.pack(length))
      pattern = '<%sh'%length
      buff.write(struct.Struct(pattern).pack(*self.sol_thrust))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.sol_ctrl, _x.sol_bear,) = _get_struct_2B().unpack(str[start:end])
      self.sol_ctrl = bool(self.sol_ctrl)
      self.sol_bear = bool(self.sol_bear)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sh'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.sol_thrust = s.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2B().pack(_x.sol_ctrl, _x.sol_bear))
      length = len(self.sol_thrust)
      buff.write(_struct_I.pack(length))
      pattern = '<%sh'%length
      buff.write(self.sol_thrust.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.sol_ctrl, _x.sol_bear,) = _get_struct_2B().unpack(str[start:end])
      self.sol_ctrl = bool(self.sol_ctrl)
      self.sol_bear = bool(self.sol_bear)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sh'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.sol_thrust = numpy.frombuffer(str[start:end], dtype=numpy.int16, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B = None
def _get_struct_2B():
    global _struct_2B
    if _struct_2B is None:
        _struct_2B = struct.Struct("<2B")
    return _struct_2B
